### ISSUE TITLE
LOCODE datastore

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/codes-locode#1]
Lets take the UN/LOCODE file published here https://unece.org/trade/cefact/UNLOCODE-Download and

## Data load:

* Load it to a dynamoDB table with properties:
  * locode (eg AEDXB)
  * country (eg AE)
  * countrySubDivision (eg DU)
  * name (eg Dubai)
  * nameWithDiacritics (same as name unless some characters have accents etc)
  * status (eg active)
  * statusDate (eg 2007-04-01)
  * authority (eg AI)
  * functions (eg [1,3,4,5])
  * IATA code (if available)
  * Latitude (eg 25.15N)
  * Longditude (eg 055.16E)

## Lat/Long Parsing

Current string like "2515N 05516E" needs to be parsed to become lat & long properties.  First two chars of Lat and first three chars of long are always before the decimal.

## Date parsing

Current 4 character number such as "0407" (which is YYMM) should map to ISO-8601 standard date in the form YYYY-MM-DD - always just use 01 for DD.  Also if YY starts with "8" or "9" then the full 4 char year is 198Y or 199Y - otherwise the year is 20YY.

## Authority codes (one per locode):
  
AA = Approved by competent national government agency
AC = Approved by Customs Authority
AF = Approved by national facilitation body
AI = Code adopted by international organisation (IATA or ECLAC)
AM = Approved by the UN/LOCODE Maintenance Agency
AS = Approved by national standardisation body
AQ = Entry approved, functions not verified
RL = Recognised location - Existence and representation of location name confirmed by
check against nominated gazetteer or other reference work
RN = Request from credible national sources for locations in their own country
RQ = Request under consideration
RR = Request rejected
QQ = Original entry not verified since date indicated
UR = Entry included on user's request; not officially approved
XX = Entry that will be removed from the next issue of UN/LOCODE 

## Status code mappings

* "proposed" if authority = RQ
* "deprecated" if authority = XX or RR
* "active" for all other values of authority.

## Function codes (one or more per Locode)

1 = port, as defined in Rec. 16
2 = rail terminal
3 = road terminal
4 = airport
5 = postal exchange office
6 = reserved for multimodal functions, ICD's, etc.
7 = reserved for fixed transport functions (e.g. oil platform)
B = border crossing
0 = function not known, to be specified

**Comment by nissimsan** [comment]
We've made a ton of progress on LOCODES LD. I suggest we close.
