### ISSUE TITLE
LOCODE API

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/codes-locode#2]
Implement a simple query API over the LOCODE data store following the API specification at https://jargon.sh/redoc.html?url=/user/unece/codes-locode/v/working/artefacts/openapi/render.json

* In a dedicated codes-locode AWS VPC
* Using AWS API-GW and caching of queries via CloudFrint.
* serverless lambda function for the query - hitting the dynamodb store as per #1 
* No authentication - but apply rate limiting.

**Comment by nissimsan** [comment]
The LD navigation works so well we don't need an API.

**Comment by nissimsan** [comment]
Reopening, let's discuss at the Forum if requirements are surfaced.
